### ISSUE TITLE
How do I make Google Lens the default OCR on startup? 

### ISSUE THREAD

**Issue by phamthaison1207** [AuroraWright/owocr#4]
Hi there, your owocr is really really useful and I recently installed a few more ocrs like rapid ocr and easy ocr as backup plans for when google lens fail but I want to know how to set the config so that it defaults to google lens on start up.

**Comment by AuroraWright** [comment]
(Already discussed on Discord, for reference it's the "engine" option in the owocr_config.ini https://github.com/AuroraWright/owocr/blob/master/owocr_config.ini#L3 )
